Fixed control start/reload bugs - Added configuration check for reload - Added wait for nginx start - Added OPENSHIFT_NGINX_PID - pgrep use current user

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -4,55 +4,68 @@ set -e
 source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
 
 export STOPTIMEOUT=20
+export STARTTIMEOUT=20
 
 NGINX_EXEC=${OPENSHIFT_NGINX_VERSION_DIR}/sbin/nginx
 NGINX_CONFIG_FILE=${OPENSHIFT_NGINX_DIR}/conf/nginx.conf
 NGINX_HTTP_CONFIG_FILE=${OPENSHIFT_NGINX_DIR}/conf/nginx_http.conf
-NGINX_PID_FILE=${OPENSHIFT_NGINX_DIR}/run/nginx.pid
 
 function isrunning() {
-    if [ -f "${NGINX_PID_FILE}" ]; then
-        pid=`cat ${NGINX_PID_FILE} 2> /dev/null`
+    if [ -f "${OPENSHIFT_NGINX_PID}" ]; then
+        local pid=`cat ${OPENSHIFT_NGINX_PID} 2> /dev/null`
         [ -z "${pid}" ]  &&  return 1
-        current_user=`id -u`
+
+        local current_user=`id -u`
         if `ps --pid ${pid} > /dev/null 2>&1` || \
-           `pgrep -x nginx > /dev/null 2>&1`; then
+           `pgrep -x nginx -u ${current_user} > /dev/null 2>&1`; then
             return 0
         fi
     fi
     return 1
 }
 
-function _nginx_start() {
-    if [ -f "${NGINX_CONFIG_FILE}" ] && [ -f "${NGINX_HTTP_CONFIG_FILE}" ]; then
-        ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR}
-    else
+function hasconfig() {
+    if [ ! -f "${NGINX_CONFIG_FILE}" ]; then
+        echo "Missing conf/nginx.conf in cartridge."
+        return 1
+    fi
+    if [ ! -f "${NGINX_HTTP_CONFIG_FILE}" ]; then
         echo "Missing .openshift/nginx.conf.erb in repo."
+        return 1
+    fi
+
+    return 0
+}
+
+function _nginx_start() {
+    if hasconfig; then
+        ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR} 2>&1
     fi
 }
 
 function _nginx_stop() {
-    [ -f "${NGINX_PID_FILE}" ] && pid=$( /bin/cat "${NGINX_PID_FILE}" )
+    [ -f "${OPENSHIFT_NGINX_PID}" ] && pid=$( /bin/cat "${OPENSHIFT_NGINX_PID}" )
 
     # Check pid file
     if `ps -p ${pid} > /dev/null 2>&1`; then
-        if [ -f "${NGINX_CONFIG_FILE}" ]; then
-            ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR} -s stop
+        if hasconfig; then
+            ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR} -s stop  2>&1
         else
-            /bin/kill ${pid}
+            /bin/kill -9 ${pid}
         fi
 
-        ret=$?
+        local ret=$?
         if [ ${ret} -eq 0 ]; then
-            TIMEOUT="${STOPTIMEOUT}"
-            while [ ${TIMEOUT} -gt 0 ] && [ -f "${NGINX_PID_FILE}" ]; do
+            local TIMEOUT="${STOPTIMEOUT}"
+            while [ ${TIMEOUT} -gt 0 ] && [ -f "${OPENSHIFT_NGINX_PID}" ]; do
                 /bin/kill -0 "${pid}" >/dev/null 2>&1 || break
                 sleep .5
                 let TIMEOUT=${TIMEOUT}-1
             done
         fi
     else
-        if `pgrep -x nginx > /dev/null 2>&1`
+        local current_user=`id -u`
+        if `pgrep -x nginx -u ${current_user} > /dev/null 2>&1`
         then
             echo "Warning: Nginx process exists without a pid file. Use force-stop to kill."
         else
@@ -63,21 +76,21 @@ function _nginx_stop() {
 
 function _nginx_update_conf() {
     CONF_FILE=${OPENSHIFT_REPO_DIR}/.openshift/nginx.conf.erb
-    if [ ! -f "${OPENSHIFT_REPO_DIR}/.openshift/nginx.conf.erb" ]; then
-        CONF_FILE=${OPENSHIFT_NGINX_DIR}/nginx_http.conf.erb
+    if [ -f "${CONF_FILE}" ]; then
+        oo-erb ${CONF_FILE} > ${NGINX_HTTP_CONFIG_FILE}
+    else
+        echo "Failed updating .openshift/nginx.conf.erb, file not found"
     fi
-
-    oo-erb ${CONF_FILE} > ${OPENSHIFT_NGINX_DIR}/conf/nginx_http.conf
 }
 
 function start() {
-    if [ isrunning ]; then
+    if isrunning; then
         _nginx_stop
     fi
 
     _nginx_update_conf
     _nginx_start
-    isrunning  &&  echo "Nginx instance is started"
+    isrunning && echo "Nginx instance is started"
 }
 
 
@@ -106,10 +119,10 @@ function status() {
 
 function reload() {
     if ! isrunning; then
-       _start_nginx
-    else
+       _nginx_start
+    elif hasconfig; then
        echo "`date`: Reloading Nginx " 1>&2
-        ${OPENSHIFT_RUNTIME_DIR}/nginx/sbin/nginx -c ${NGINX_CONFIG_FILE} -s reload
+        ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -s reload 2>&1
     fi
 
     isrunning  &&  echo "Reloaded Nginx instance"
