Updated setup and compile to use LFS

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,17 +1,30 @@
 #!/bin/bash
 set -e
 
+source "${OPENSHIFT_NGINX_DIR}/bin/setup_util.sh"
+
+# LFS configuration
+LFS_ENDPOINT=https://github.com/boekkooi/openshift-cartridge-nginx.git/info/lfs
+
+# Resolve version
 case "$1" in
   -v|--version)
     version="$2"
 esac
 
-# Resolve version
 NGINX_VERSION=1.9.12
-if [ ! -z "${OPENSHIFT_NGINX_VERSION}" ] && [ -d "${OPENSHIFT_NGINX_DIR}/usr/nginx-${OPENSHIFT_NGINX_VERSION}/" ]; then
+if [ ! -z "${OPENSHIFT_NGINX_VERSION}" ] && [ -f "${OPENSHIFT_NGINX_DIR}/usr/nginx-${OPENSHIFT_NGINX_VERSION}.tar.gz" ]; then
     NGINX_VERSION="${OPENSHIFT_NGINX_VERSION}"
-elif [ -d "${OPENSHIFT_NGINX_DIR}/usr/nginx-${version}/" ]; then
+elif [ -f "${OPENSHIFT_NGINX_DIR}/usr/nginx-${version}.tar.gz" ]; then
     NGINX_VERSION="${version}"
+fi
+NGINX_VERSION_DIR="${OPENSHIFT_NGINX_DIR}/usr/nginx-${NGINX_VERSION}"
+
+# Download and extract PHP version from LFS
+lfs_download_and_extact
+if [ ! -d "${NGINX_VERSION_DIR}" ]; then
+    echo "Failed to download and extract nginx from LFS"
+    exit 1
 fi
 
 # Create dirs
@@ -24,4 +37,4 @@ done
 export OPENSHIFT_NGINX_VERSION=${NGINX_VERSION}
 
 echo "${NGINX_VERSION}" > ${OPENSHIFT_NGINX_DIR}/env/OPENSHIFT_NGINX_VERSION
-echo "${OPENSHIFT_NGINX_DIR}/usr/nginx-${OPENSHIFT_NGINX_VERSION}" > ${OPENSHIFT_NGINX_DIR}/env/OPENSHIFT_NGINX_VERSION_DIR
+echo "${NGINX_VERSION_DIR}" > ${OPENSHIFT_NGINX_DIR}/env/OPENSHIFT_NGINX_VERSION_DIR
